// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ethgrpc.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetSyncRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSyncRequest) Reset()         { *m = GetSyncRequest{} }
func (m *GetSyncRequest) String() string { return proto.CompactTextString(m) }
func (*GetSyncRequest) ProtoMessage()    {}
func (*GetSyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b58a0e0835cfa32, []int{0}
}

func (m *GetSyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSyncRequest.Unmarshal(m, b)
}
func (m *GetSyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSyncRequest.Marshal(b, m, deterministic)
}
func (m *GetSyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSyncRequest.Merge(m, src)
}
func (m *GetSyncRequest) XXX_Size() int {
	return xxx_messageInfo_GetSyncRequest.Size(m)
}
func (m *GetSyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSyncRequest proto.InternalMessageInfo

type GetSyncResponse struct {
	StartingBlock        string   `protobuf:"bytes,1,opt,name=startingBlock,proto3" json:"startingBlock,omitempty"`
	CurrentBlock         string   `protobuf:"bytes,2,opt,name=currentBlock,proto3" json:"currentBlock,omitempty"`
	HighestBlock         string   `protobuf:"bytes,3,opt,name=highestBlock,proto3" json:"highestBlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSyncResponse) Reset()         { *m = GetSyncResponse{} }
func (m *GetSyncResponse) String() string { return proto.CompactTextString(m) }
func (*GetSyncResponse) ProtoMessage()    {}
func (*GetSyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b58a0e0835cfa32, []int{1}
}

func (m *GetSyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSyncResponse.Unmarshal(m, b)
}
func (m *GetSyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSyncResponse.Marshal(b, m, deterministic)
}
func (m *GetSyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSyncResponse.Merge(m, src)
}
func (m *GetSyncResponse) XXX_Size() int {
	return xxx_messageInfo_GetSyncResponse.Size(m)
}
func (m *GetSyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSyncResponse proto.InternalMessageInfo

func (m *GetSyncResponse) GetStartingBlock() string {
	if m != nil {
		return m.StartingBlock
	}
	return ""
}

func (m *GetSyncResponse) GetCurrentBlock() string {
	if m != nil {
		return m.CurrentBlock
	}
	return ""
}

func (m *GetSyncResponse) GetHighestBlock() string {
	if m != nil {
		return m.HighestBlock
	}
	return ""
}

type GetTxsForBlockHashRequest struct {
	BlockHash            string   `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTxsForBlockHashRequest) Reset()         { *m = GetTxsForBlockHashRequest{} }
func (m *GetTxsForBlockHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetTxsForBlockHashRequest) ProtoMessage()    {}
func (*GetTxsForBlockHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b58a0e0835cfa32, []int{2}
}

func (m *GetTxsForBlockHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxsForBlockHashRequest.Unmarshal(m, b)
}
func (m *GetTxsForBlockHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxsForBlockHashRequest.Marshal(b, m, deterministic)
}
func (m *GetTxsForBlockHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxsForBlockHashRequest.Merge(m, src)
}
func (m *GetTxsForBlockHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetTxsForBlockHashRequest.Size(m)
}
func (m *GetTxsForBlockHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxsForBlockHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxsForBlockHashRequest proto.InternalMessageInfo

func (m *GetTxsForBlockHashRequest) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

type Transaction struct {
	BlockHash            string   `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	BlockNumber          string   `protobuf:"bytes,2,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Gas                  string   `protobuf:"bytes,4,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice             string   `protobuf:"bytes,5,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	Hash                 string   `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	Input                string   `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`
	Nonce                string   `protobuf:"bytes,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	To                   string   `protobuf:"bytes,9,opt,name=to,proto3" json:"to,omitempty"`
	TransactionIndex     string   `protobuf:"bytes,10,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	Value                string   `protobuf:"bytes,11,opt,name=value,proto3" json:"value,omitempty"`
	V                    string   `protobuf:"bytes,12,opt,name=v,proto3" json:"v,omitempty"`
	R                    string   `protobuf:"bytes,13,opt,name=r,proto3" json:"r,omitempty"`
	S                    string   `protobuf:"bytes,14,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b58a0e0835cfa32, []int{3}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Transaction) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *Transaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Transaction) GetGas() string {
	if m != nil {
		return m.Gas
	}
	return ""
}

func (m *Transaction) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Transaction) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *Transaction) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetTransactionIndex() string {
	if m != nil {
		return m.TransactionIndex
	}
	return ""
}

func (m *Transaction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Transaction) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *Transaction) GetR() string {
	if m != nil {
		return m.R
	}
	return ""
}

func (m *Transaction) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

type GetTxsForBlockHashResponse struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetTxsForBlockHashResponse) Reset()         { *m = GetTxsForBlockHashResponse{} }
func (m *GetTxsForBlockHashResponse) String() string { return proto.CompactTextString(m) }
func (*GetTxsForBlockHashResponse) ProtoMessage()    {}
func (*GetTxsForBlockHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b58a0e0835cfa32, []int{4}
}

func (m *GetTxsForBlockHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxsForBlockHashResponse.Unmarshal(m, b)
}
func (m *GetTxsForBlockHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxsForBlockHashResponse.Marshal(b, m, deterministic)
}
func (m *GetTxsForBlockHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxsForBlockHashResponse.Merge(m, src)
}
func (m *GetTxsForBlockHashResponse) XXX_Size() int {
	return xxx_messageInfo_GetTxsForBlockHashResponse.Size(m)
}
func (m *GetTxsForBlockHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxsForBlockHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxsForBlockHashResponse proto.InternalMessageInfo

func (m *GetTxsForBlockHashResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*GetSyncRequest)(nil), "main.GetSyncRequest")
	proto.RegisterType((*GetSyncResponse)(nil), "main.GetSyncResponse")
	proto.RegisterType((*GetTxsForBlockHashRequest)(nil), "main.GetTxsForBlockHashRequest")
	proto.RegisterType((*Transaction)(nil), "main.Transaction")
	proto.RegisterType((*GetTxsForBlockHashResponse)(nil), "main.GetTxsForBlockHashResponse")
}

func init() { proto.RegisterFile("ethgrpc.proto", fileDescriptor_7b58a0e0835cfa32) }

var fileDescriptor_7b58a0e0835cfa32 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcd, 0x8e, 0xd3, 0x30,
	0x14, 0x85, 0x95, 0xb4, 0x33, 0x9d, 0xde, 0xa4, 0xa5, 0x5c, 0x0d, 0x92, 0x89, 0x90, 0x88, 0x22,
	0x16, 0x23, 0x16, 0x5d, 0x0c, 0x02, 0x89, 0x2d, 0x08, 0x0a, 0x1b, 0x34, 0x4a, 0x2b, 0xb1, 0x76,
	0x83, 0x49, 0x22, 0x5a, 0x3b, 0xd8, 0x4e, 0x55, 0x56, 0xbc, 0x07, 0xaf, 0xc4, 0x4b, 0x21, 0xff,
	0xd0, 0x26, 0xb4, 0xcc, 0xce, 0xe7, 0xcb, 0xc9, 0xbd, 0x27, 0xf2, 0x09, 0x4c, 0x98, 0xae, 0x4a,
	0xd9, 0x14, 0xf3, 0x46, 0x0a, 0x2d, 0x70, 0xb8, 0xa5, 0x35, 0xcf, 0x66, 0x30, 0x5d, 0x30, 0xbd,
	0xfc, 0xc1, 0x8b, 0x9c, 0x7d, 0x6f, 0x99, 0xd2, 0xd9, 0x4f, 0x78, 0x70, 0x20, 0xaa, 0x11, 0x5c,
	0x31, 0x7c, 0x06, 0x13, 0xa5, 0xa9, 0xd4, 0x35, 0x2f, 0xdf, 0x6c, 0x44, 0xf1, 0x8d, 0x04, 0x69,
	0x70, 0x33, 0xce, 0xfb, 0x10, 0x33, 0x88, 0x8b, 0x56, 0x4a, 0xc6, 0xb5, 0x33, 0x85, 0xd6, 0xd4,
	0x63, 0xc6, 0x53, 0xd5, 0x65, 0xc5, 0x94, 0xf7, 0x0c, 0x9c, 0xa7, 0xcb, 0xb2, 0xd7, 0xf0, 0x78,
	0xc1, 0xf4, 0x6a, 0xaf, 0xde, 0x0b, 0x69, 0xc9, 0x07, 0xaa, 0x2a, 0x9f, 0x0e, 0x9f, 0xc0, 0x78,
	0xfd, 0x97, 0xf9, 0x18, 0x47, 0x90, 0xfd, 0x0e, 0x21, 0x5a, 0x49, 0xca, 0x15, 0x2d, 0x74, 0x2d,
	0xf8, 0xfd, 0x6e, 0x4c, 0x21, 0xb2, 0xe2, 0x53, 0xbb, 0x5d, 0x33, 0xe9, 0xf3, 0x76, 0x11, 0x22,
	0x0c, 0xbf, 0x4a, 0xb1, 0xf5, 0x31, 0xed, 0x19, 0x67, 0x30, 0x28, 0xa9, 0x22, 0x43, 0x8b, 0xcc,
	0x11, 0x13, 0xb8, 0x2a, 0xa9, 0xba, 0x93, 0x75, 0xc1, 0xc8, 0x85, 0xc5, 0x07, 0x6d, 0x26, 0x54,
	0x66, 0xf9, 0xa5, 0x9b, 0x60, 0xce, 0x78, 0x0d, 0x17, 0x35, 0x6f, 0x5a, 0x4d, 0x46, 0x16, 0x3a,
	0x61, 0x28, 0x17, 0xbc, 0x60, 0xe4, 0xca, 0x51, 0x2b, 0x70, 0x0a, 0xa1, 0x16, 0x64, 0x6c, 0x51,
	0xa8, 0x05, 0x3e, 0x87, 0x99, 0x3e, 0x7e, 0xe0, 0x47, 0xfe, 0x85, 0xed, 0x09, 0xd8, 0xa7, 0x27,
	0xdc, 0x4c, 0xdc, 0xd1, 0x4d, 0xcb, 0x48, 0xe4, 0x26, 0x5a, 0x81, 0x31, 0x04, 0x3b, 0x12, 0x5b,
	0x12, 0xec, 0x8c, 0x92, 0x64, 0xe2, 0x94, 0x34, 0x4a, 0x91, 0xa9, 0x53, 0x2a, 0x5b, 0x42, 0x72,
	0xee, 0x22, 0x7c, 0x29, 0x5e, 0x42, 0xdc, 0xd9, 0xa8, 0x48, 0x90, 0x0e, 0x6e, 0xa2, 0xdb, 0x87,
	0x73, 0x53, 0xab, 0x79, 0xe7, 0x12, 0xf2, 0x9e, 0xed, 0xf6, 0x57, 0x00, 0xa3, 0x77, 0xba, 0x5a,
	0xe4, 0x77, 0x6f, 0xf1, 0x15, 0x8c, 0x7c, 0xd5, 0xf0, 0xda, 0xbd, 0xd7, 0xef, 0x62, 0xf2, 0xe8,
	0x1f, 0xea, 0x57, 0x7f, 0x06, 0x3c, 0x0d, 0x86, 0x4f, 0x0f, 0xe6, 0xf3, 0xdd, 0x49, 0xd2, 0xff,
	0x1b, 0xdc, 0xe0, 0xf5, 0xa5, 0xfd, 0x35, 0x5e, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x99,
	0xea, 0xf8, 0x2b, 0x03, 0x00, 0x00,
}
