// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ethgrpc.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetSyncRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSyncRequest) Reset()         { *m = GetSyncRequest{} }
func (m *GetSyncRequest) String() string { return proto.CompactTextString(m) }
func (*GetSyncRequest) ProtoMessage()    {}
func (*GetSyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b58a0e0835cfa32, []int{0}
}

func (m *GetSyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSyncRequest.Unmarshal(m, b)
}
func (m *GetSyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSyncRequest.Marshal(b, m, deterministic)
}
func (m *GetSyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSyncRequest.Merge(m, src)
}
func (m *GetSyncRequest) XXX_Size() int {
	return xxx_messageInfo_GetSyncRequest.Size(m)
}
func (m *GetSyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSyncRequest proto.InternalMessageInfo

type SyncInfo struct {
	StartingBlock        string   `protobuf:"bytes,1,opt,name=startingBlock,proto3" json:"startingBlock,omitempty"`
	CurrentBlock         string   `protobuf:"bytes,2,opt,name=currentBlock,proto3" json:"currentBlock,omitempty"`
	HighestBlock         string   `protobuf:"bytes,3,opt,name=highestBlock,proto3" json:"highestBlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncInfo) Reset()         { *m = SyncInfo{} }
func (m *SyncInfo) String() string { return proto.CompactTextString(m) }
func (*SyncInfo) ProtoMessage()    {}
func (*SyncInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b58a0e0835cfa32, []int{1}
}

func (m *SyncInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInfo.Unmarshal(m, b)
}
func (m *SyncInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInfo.Marshal(b, m, deterministic)
}
func (m *SyncInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInfo.Merge(m, src)
}
func (m *SyncInfo) XXX_Size() int {
	return xxx_messageInfo_SyncInfo.Size(m)
}
func (m *SyncInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInfo proto.InternalMessageInfo

func (m *SyncInfo) GetStartingBlock() string {
	if m != nil {
		return m.StartingBlock
	}
	return ""
}

func (m *SyncInfo) GetCurrentBlock() string {
	if m != nil {
		return m.CurrentBlock
	}
	return ""
}

func (m *SyncInfo) GetHighestBlock() string {
	if m != nil {
		return m.HighestBlock
	}
	return ""
}

type GetSyncResponse struct {
	Status               string    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage         string    `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	SyncInfo             *SyncInfo `protobuf:"bytes,3,opt,name=syncInfo,proto3" json:"syncInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetSyncResponse) Reset()         { *m = GetSyncResponse{} }
func (m *GetSyncResponse) String() string { return proto.CompactTextString(m) }
func (*GetSyncResponse) ProtoMessage()    {}
func (*GetSyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b58a0e0835cfa32, []int{2}
}

func (m *GetSyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSyncResponse.Unmarshal(m, b)
}
func (m *GetSyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSyncResponse.Marshal(b, m, deterministic)
}
func (m *GetSyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSyncResponse.Merge(m, src)
}
func (m *GetSyncResponse) XXX_Size() int {
	return xxx_messageInfo_GetSyncResponse.Size(m)
}
func (m *GetSyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSyncResponse proto.InternalMessageInfo

func (m *GetSyncResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetSyncResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetSyncResponse) GetSyncInfo() *SyncInfo {
	if m != nil {
		return m.SyncInfo
	}
	return nil
}

type GetTxsForBlockHashRequest struct {
	BlockHash            string   `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTxsForBlockHashRequest) Reset()         { *m = GetTxsForBlockHashRequest{} }
func (m *GetTxsForBlockHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetTxsForBlockHashRequest) ProtoMessage()    {}
func (*GetTxsForBlockHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b58a0e0835cfa32, []int{3}
}

func (m *GetTxsForBlockHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxsForBlockHashRequest.Unmarshal(m, b)
}
func (m *GetTxsForBlockHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxsForBlockHashRequest.Marshal(b, m, deterministic)
}
func (m *GetTxsForBlockHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxsForBlockHashRequest.Merge(m, src)
}
func (m *GetTxsForBlockHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetTxsForBlockHashRequest.Size(m)
}
func (m *GetTxsForBlockHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxsForBlockHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxsForBlockHashRequest proto.InternalMessageInfo

func (m *GetTxsForBlockHashRequest) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

type Transaction struct {
	BlockHash            string   `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	BlockNumber          string   `protobuf:"bytes,2,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Gas                  string   `protobuf:"bytes,4,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice             string   `protobuf:"bytes,5,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	Hash                 string   `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	Input                string   `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`
	Nonce                string   `protobuf:"bytes,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	To                   string   `protobuf:"bytes,9,opt,name=to,proto3" json:"to,omitempty"`
	TransactionIndex     string   `protobuf:"bytes,10,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	Value                string   `protobuf:"bytes,11,opt,name=value,proto3" json:"value,omitempty"`
	V                    string   `protobuf:"bytes,12,opt,name=v,proto3" json:"v,omitempty"`
	R                    string   `protobuf:"bytes,13,opt,name=r,proto3" json:"r,omitempty"`
	S                    string   `protobuf:"bytes,14,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b58a0e0835cfa32, []int{4}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Transaction) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *Transaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Transaction) GetGas() string {
	if m != nil {
		return m.Gas
	}
	return ""
}

func (m *Transaction) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Transaction) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *Transaction) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetTransactionIndex() string {
	if m != nil {
		return m.TransactionIndex
	}
	return ""
}

func (m *Transaction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Transaction) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *Transaction) GetR() string {
	if m != nil {
		return m.R
	}
	return ""
}

func (m *Transaction) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

type GetTxsForBlockHashResponse struct {
	Status               string         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage         string         `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetTxsForBlockHashResponse) Reset()         { *m = GetTxsForBlockHashResponse{} }
func (m *GetTxsForBlockHashResponse) String() string { return proto.CompactTextString(m) }
func (*GetTxsForBlockHashResponse) ProtoMessage()    {}
func (*GetTxsForBlockHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b58a0e0835cfa32, []int{5}
}

func (m *GetTxsForBlockHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxsForBlockHashResponse.Unmarshal(m, b)
}
func (m *GetTxsForBlockHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxsForBlockHashResponse.Marshal(b, m, deterministic)
}
func (m *GetTxsForBlockHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxsForBlockHashResponse.Merge(m, src)
}
func (m *GetTxsForBlockHashResponse) XXX_Size() int {
	return xxx_messageInfo_GetTxsForBlockHashResponse.Size(m)
}
func (m *GetTxsForBlockHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxsForBlockHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxsForBlockHashResponse proto.InternalMessageInfo

func (m *GetTxsForBlockHashResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetTxsForBlockHashResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetTxsForBlockHashResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*GetSyncRequest)(nil), "proto.GetSyncRequest")
	proto.RegisterType((*SyncInfo)(nil), "proto.SyncInfo")
	proto.RegisterType((*GetSyncResponse)(nil), "proto.GetSyncResponse")
	proto.RegisterType((*GetTxsForBlockHashRequest)(nil), "proto.GetTxsForBlockHashRequest")
	proto.RegisterType((*Transaction)(nil), "proto.Transaction")
	proto.RegisterType((*GetTxsForBlockHashResponse)(nil), "proto.GetTxsForBlockHashResponse")
}

func init() { proto.RegisterFile("ethgrpc.proto", fileDescriptor_7b58a0e0835cfa32) }

var fileDescriptor_7b58a0e0835cfa32 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xe5, 0xa4, 0xf9, 0x1a, 0x27, 0x69, 0x34, 0x82, 0x6a, 0x89, 0x38, 0x04, 0x8b, 0x43,
	0x05, 0x52, 0x0f, 0x41, 0x42, 0x70, 0x05, 0x41, 0xe8, 0x01, 0x54, 0x99, 0x5e, 0x38, 0x6e, 0xcc,
	0xd6, 0xb6, 0x68, 0x77, 0xcd, 0xce, 0x3a, 0x0a, 0x3c, 0x05, 0x4f, 0xc0, 0x0b, 0xf1, 0x52, 0x68,
	0x3f, 0x92, 0xd8, 0xb4, 0xea, 0x89, 0x93, 0xe7, 0xff, 0xf3, 0xdf, 0xf3, 0xb1, 0x3b, 0x86, 0x89,
	0x30, 0x45, 0xae, 0xab, 0xec, 0xac, 0xd2, 0xca, 0x28, 0xec, 0xb9, 0x47, 0x32, 0x83, 0xe9, 0x4a,
	0x98, 0xcf, 0x3f, 0x64, 0x96, 0x8a, 0xef, 0xb5, 0x20, 0x93, 0x6c, 0x61, 0x68, 0xe5, 0xb9, 0xbc,
	0x52, 0xf8, 0x14, 0x26, 0x64, 0xb8, 0x36, 0xa5, 0xcc, 0xdf, 0x5c, 0xab, 0xec, 0x1b, 0x8b, 0x16,
	0xd1, 0xe9, 0x28, 0x6d, 0x43, 0x4c, 0x60, 0x9c, 0xd5, 0x5a, 0x0b, 0x69, 0xbc, 0xa9, 0xe3, 0x4c,
	0x2d, 0x66, 0x3d, 0x45, 0x99, 0x17, 0x82, 0x82, 0xa7, 0xeb, 0x3d, 0x4d, 0x96, 0xfc, 0x84, 0xe3,
	0x7d, 0x2f, 0x54, 0x29, 0x49, 0x02, 0x4f, 0xa0, 0x4f, 0x86, 0x9b, 0x9a, 0x42, 0xe5, 0xa0, 0x6c,
	0x3a, 0xa1, 0xb5, 0xd2, 0x1f, 0x05, 0x11, 0xcf, 0xc5, 0xae, 0x64, 0x93, 0xe1, 0x73, 0x18, 0x52,
	0x18, 0xc4, 0x95, 0x8b, 0x97, 0xc7, 0x7e, 0xf6, 0xb3, 0xdd, 0x7c, 0xe9, 0xde, 0x90, 0xbc, 0x86,
	0x47, 0x2b, 0x61, 0x2e, 0xb7, 0xf4, 0x5e, 0x69, 0xd7, 0xcd, 0x07, 0x4e, 0x45, 0x38, 0x12, 0x7c,
	0x0c, 0xa3, 0xf5, 0x8e, 0x85, 0x46, 0x0e, 0x20, 0xf9, 0xd3, 0x81, 0xf8, 0x52, 0x73, 0x49, 0x3c,
	0x33, 0xa5, 0x92, 0xf7, 0xbb, 0x71, 0x01, 0xb1, 0x13, 0x9f, 0xea, 0x9b, 0xb5, 0xd0, 0xa1, 0xf1,
	0x26, 0x42, 0x84, 0xa3, 0x2b, 0xad, 0x6e, 0xc2, 0x11, 0xb9, 0x18, 0x67, 0xd0, 0xcd, 0x39, 0xb1,
	0x23, 0x87, 0x6c, 0x88, 0x73, 0x18, 0xe6, 0x9c, 0x2e, 0x74, 0x99, 0x09, 0xd6, 0x73, 0x78, 0xaf,
	0x6d, 0x86, 0xc2, 0x16, 0xef, 0xfb, 0x0c, 0x36, 0xc6, 0x07, 0xd0, 0x2b, 0x65, 0x55, 0x1b, 0x36,
	0x70, 0xd0, 0x0b, 0x4b, 0xa5, 0x92, 0x99, 0x60, 0x43, 0x4f, 0x9d, 0xc0, 0x29, 0x74, 0x8c, 0x62,
	0x23, 0x87, 0x3a, 0x46, 0xe1, 0x33, 0x98, 0x99, 0xc3, 0x80, 0xe7, 0xf2, 0xab, 0xd8, 0x32, 0x70,
	0x6f, 0x6f, 0x71, 0x9b, 0x71, 0xc3, 0xaf, 0x6b, 0xc1, 0x62, 0x9f, 0xd1, 0x09, 0x1c, 0x43, 0xb4,
	0x61, 0x63, 0x47, 0xa2, 0x8d, 0x55, 0x9a, 0x4d, 0xbc, 0xd2, 0x56, 0x11, 0x9b, 0x7a, 0x45, 0xc9,
	0xaf, 0x08, 0xe6, 0x77, 0xdd, 0xc4, 0x7f, 0x58, 0x88, 0x97, 0x30, 0x6e, 0xb4, 0x4b, 0xac, 0xbb,
	0xe8, 0x9e, 0xc6, 0x4b, 0x0c, 0x4b, 0xd1, 0xb8, 0xc2, 0xb4, 0xe5, 0x5b, 0xfe, 0x8e, 0x60, 0xf0,
	0xce, 0x14, 0xab, 0xf4, 0xe2, 0x2d, 0xbe, 0x82, 0x41, 0xd8, 0x51, 0x7c, 0x18, 0x3e, 0x6c, 0xff,
	0x3f, 0xf3, 0x93, 0x7f, 0x71, 0xe8, 0xfc, 0x0b, 0xe0, 0xed, 0xb9, 0x70, 0x71, 0x70, 0xdf, 0xbd,
	0x7c, 0xf3, 0x27, 0xf7, 0x38, 0x7c, 0xea, 0x75, 0xdf, 0x39, 0x5e, 0xfc, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0x7c, 0x77, 0x0e, 0x28, 0xe3, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EthGRPCClient is the client API for EthGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EthGRPCClient interface {
	GetSync(ctx context.Context, in *GetSyncRequest, opts ...grpc.CallOption) (*GetSyncResponse, error)
	GetTxsForBlockHash(ctx context.Context, in *GetTxsForBlockHashRequest, opts ...grpc.CallOption) (*GetTxsForBlockHashResponse, error)
}

type ethGRPCClient struct {
	cc *grpc.ClientConn
}

func NewEthGRPCClient(cc *grpc.ClientConn) EthGRPCClient {
	return &ethGRPCClient{cc}
}

func (c *ethGRPCClient) GetSync(ctx context.Context, in *GetSyncRequest, opts ...grpc.CallOption) (*GetSyncResponse, error) {
	out := new(GetSyncResponse)
	err := c.cc.Invoke(ctx, "/proto.EthGRPC/GetSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethGRPCClient) GetTxsForBlockHash(ctx context.Context, in *GetTxsForBlockHashRequest, opts ...grpc.CallOption) (*GetTxsForBlockHashResponse, error) {
	out := new(GetTxsForBlockHashResponse)
	err := c.cc.Invoke(ctx, "/proto.EthGRPC/GetTxsForBlockHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EthGRPCServer is the server API for EthGRPC service.
type EthGRPCServer interface {
	GetSync(context.Context, *GetSyncRequest) (*GetSyncResponse, error)
	GetTxsForBlockHash(context.Context, *GetTxsForBlockHashRequest) (*GetTxsForBlockHashResponse, error)
}

func RegisterEthGRPCServer(s *grpc.Server, srv EthGRPCServer) {
	s.RegisterService(&_EthGRPC_serviceDesc, srv)
}

func _EthGRPC_GetSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthGRPCServer).GetSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EthGRPC/GetSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthGRPCServer).GetSync(ctx, req.(*GetSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthGRPC_GetTxsForBlockHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxsForBlockHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthGRPCServer).GetTxsForBlockHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EthGRPC/GetTxsForBlockHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthGRPCServer).GetTxsForBlockHash(ctx, req.(*GetTxsForBlockHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EthGRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EthGRPC",
	HandlerType: (*EthGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSync",
			Handler:    _EthGRPC_GetSync_Handler,
		},
		{
			MethodName: "GetTxsForBlockHash",
			Handler:    _EthGRPC_GetTxsForBlockHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ethgrpc.proto",
}
